defmodule Rayex.Keys do
  @moduledoc false

  defmacro __using__(_) do
    quote do
      defmacro key_null do quote do: 0 end
      defmacro key_apostrophe do quote do: 39 end
      defmacro key_comma do quote do: 44 end
      defmacro key_minus do quote do: 45 end
      defmacro key_period do quote do: 46 end
      defmacro key_slash do quote do: 47 end
      defmacro key_zero do quote do: 48 end
      defmacro key_one do quote do: 49 end
      defmacro key_two do quote do: 50 end
      defmacro key_three do quote do: 51 end
      defmacro key_four do quote do: 52 end
      defmacro key_five do quote do: 53 end
      defmacro key_six do quote do: 54 end
      defmacro key_seven do quote do: 55 end
      defmacro key_eight do quote do: 56 end
      defmacro key_nine do quote do: 57 end
      defmacro key_semicolon do quote do: 59 end
      defmacro key_equal do quote do: 61 end
      defmacro key_a do quote do: 65 end
      defmacro key_b do quote do: 66 end
      defmacro key_c do quote do: 67 end
      defmacro key_d do quote do: 68 end
      defmacro key_e do quote do: 69 end
      defmacro key_f do quote do: 70 end
      defmacro key_g do quote do: 71 end
      defmacro key_h do quote do: 72 end
      defmacro key_i do quote do: 73 end
      defmacro key_j do quote do: 74 end
      defmacro key_k do quote do: 75 end
      defmacro key_l do quote do: 76 end
      defmacro key_m do quote do: 77 end
      defmacro key_n do quote do: 78 end
      defmacro key_o do quote do: 79 end
      defmacro key_p do quote do: 80 end
      defmacro key_q do quote do: 81 end
      defmacro key_r do quote do: 82 end
      defmacro key_s do quote do: 83 end
      defmacro key_t do quote do: 84 end
      defmacro key_u do quote do: 85 end
      defmacro key_v do quote do: 86 end
      defmacro key_w do quote do: 87 end
      defmacro key_x do quote do: 88 end
      defmacro key_y do quote do: 89 end
      defmacro key_z do quote do: 90 end
      defmacro key_left_bracket do quote do: 91 end
      defmacro key_backslash do quote do: 92 end
      defmacro key_right_bracket do quote do: 93 end
      defmacro key_grave do quote do: 96 end
      defmacro key_space do quote do: 32 end
      defmacro key_escape do quote do: 256 end
      defmacro key_enter do quote do: 257 end
      defmacro key_tab do quote do: 258 end
      defmacro key_backspace do quote do: 259 end
      defmacro key_insert do quote do: 260 end
      defmacro key_delete do quote do: 261 end
      defmacro key_right do quote do: 262 end
      defmacro key_left do quote do: 263 end
      defmacro key_down do quote do: 264 end
      defmacro key_up do quote do: 265 end
      defmacro key_page_up do quote do: 266 end
      defmacro key_page_down do quote do: 267 end
      defmacro key_home do quote do: 268 end
      defmacro key_end do quote do: 269 end
      defmacro key_caps_lock do quote do: 280 end
      defmacro key_scroll_lock do quote do: 281 end
      defmacro key_num_lock do quote do: 282 end
      defmacro key_print_screen do quote do: 283 end
      defmacro key_pause do quote do: 284 end
      defmacro key_f1 do quote do: 290 end
      defmacro key_f2 do quote do: 291 end
      defmacro key_f3 do quote do: 292 end
      defmacro key_f4 do quote do: 293 end
      defmacro key_f5 do quote do: 294 end
      defmacro key_f6 do quote do: 295 end
      defmacro key_f7 do quote do: 296 end
      defmacro key_f8 do quote do: 297 end
      defmacro key_f9 do quote do: 298 end
      defmacro key_f10 do quote do: 299 end
      defmacro key_f11 do quote do: 300 end
      defmacro key_f12 do quote do: 301 end
      defmacro key_left_shift do quote do: 340 end
      defmacro key_left_control do quote do: 341 end
      defmacro key_left_alt do quote do: 342 end
      defmacro key_left_super do quote do: 343 end
      defmacro key_right_shift do quote do: 344 end
      defmacro key_right_control do quote do: 345 end
      defmacro key_right_alt do quote do: 346 end
      defmacro key_right_super do quote do: 347 end
      defmacro key_kb_menu do quote do: 348 end
      defmacro key_kp_0 do quote do: 320 end
      defmacro key_kp_1 do quote do: 321 end
      defmacro key_kp_2 do quote do: 322 end
      defmacro key_kp_3 do quote do: 323 end
      defmacro key_kp_4 do quote do: 324 end
      defmacro key_kp_5 do quote do: 325 end
      defmacro key_kp_6 do quote do: 326 end
      defmacro key_kp_7 do quote do: 327 end
      defmacro key_kp_8 do quote do: 328 end
      defmacro key_kp_9 do quote do: 329 end
      defmacro key_kp_decimal do quote do: 330 end
      defmacro key_kp_divide do quote do: 331 end
      defmacro key_kp_multiply do quote do: 332 end
      defmacro key_kp_subtract do quote do: 333 end
      defmacro key_kp_add do quote do: 334 end
      defmacro key_kp_enter do quote do: 335 end
      defmacro key_kp_equal do quote do: 336 end
      defmacro key_back do quote do: 4 end
      defmacro key_menu do quote do: 82 end
      defmacro key_volume_up do quote do: 24 end
      defmacro key_volume_down do quote do: 25 end
    end
  end

end
